Fix command type in action message

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -33,6 +33,6 @@ jobs:
 
     steps:
       - name: Check code formatting with Prettier
-        run: yarn prettier:check || echo "Prettier check failed. Make sure you run 'yarn prettier-format' to format your code."
+        run: yarn prettier:check || echo "Prettier check failed. Make sure you run 'yarn prettier:format' to format your code."
 
 
